config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subreddits do
    resources :articles, shallow: true
  end

  get 'r/:slug' => 'subreddits#show', as: :subreddit_slug

  resources :moderators

  root 'subreddits#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :as => :commentable
  belongs_to :subreddit
  belongs_to :user

  validates :title, presence: true, length: { minimum: 1 }
  # Note: this regex is imperfect.
  VALID_URL_REGEX = /https?:\/\/[\S]+/
  validates :url, presence: true,
            unless: "body.present?"
  validates :url, absence: true, if: "body.present?"
  validates :body, presence: true, unless: "url.present?"
  validates :body, absence: true, if: "url.present?"
  validates :url, format:  { with: VALID_URL_REGEX }, allow_blank: true
  validates :subreddit, presence: true

  def view_link(own_path)
    (url.nil? or url.empty?)? own_path: url
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @subreddit = Subreddit.find(params[:subreddit_id])
    @article.subreddit_id = @subreddit.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to subreddit_slug_path(@subreddit.slug), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors,
                           status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors,
                           status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :url, :subreddit_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<li>
  <%= link_to article.title, article.view_link(article_path(article)) %>
  <% if user_signed_in? and current_user.moderates? article.subreddit %>
    | <%= link_to "delete", article, method: :delete,
    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/articles/_form.html.erb
<%= form_for(@article, url: subreddit_articles_path) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Url</th>
      <th>Subreddit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.url %></td>
        <td><%= article.subreddit %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', subreddit_articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<!-- <p>
  <strong>Url:</strong>
  <%= @article.url %>
</p> -->

<p>
  <strong>Subreddit:</strong>
  <%= @article.subreddit %>
</p>