config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subreddits do
    resources :articles, shallow: true
  end

  get 'r/:slug' => 'subreddits#show', as: :subreddit_slug

  resources :moderators

  root 'subreddits#index'

end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
  before_validation :generate_slug, on: :create

  validates :title, presence: true, length: { minimum: 1, maximum: 21 },
            uniqueness: { case_sensitive: false }
  validates :slug, presence: true, length: { minimum: 1, maximum: 21 },
            uniqueness: { case_sensitive: false }, format: /\A[A-Za-z0-9]*\Z/

  has_many :articles
  belongs_to :user
  has_many :moderators

  private

    def generate_slug
      self.slug = title.downcase.gsub(/[^A-Za-z0-9]/, "")
    end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :set_subreddit, only: [:edit, :update, :destroy]

  # GET /subreddits
  # GET /subreddits.json
  def index
    @subreddits = Subreddit.all
  end

  def show
    @subreddit = Subreddit.find_by(slug: params[:slug])
    head :not_found if @subreddit.nil?
  end

  # GET /subreddits/new
  def new
    @subreddit = Subreddit.new
  end

  # GET /subreddits/1/edit
  def edit
  end

  # POST /subreddits
  # POST /subreddits.json
  def create
    @subreddit = Subreddit.new(subreddit_params)
    respond_to do |format|
      if @subreddit.save
        format.html { redirect_to subreddit_slug_path(@subreddit.slug), notice: 'Subreddit was successfully created.' }
        format.json { render :show, status: :created, location: @subreddit }
      else
        format.html { render :new }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subreddits/1
  # PATCH/PUT /subreddits/1.json
  def update
    respond_to do |format|
      if @subreddit.update(subreddit_params)
        format.html { redirect_to @subreddit, notice: 'Subreddit was successfully updated.' }
        format.json { render :show, status: :ok, location: @subreddit }
      else
        format.html { render :edit }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subreddits/1
  # DELETE /subreddits/1.json
  def destroy
    @subreddit.destroy
    respond_to do |format|
      format.html { redirect_to subreddits_url, notice: 'Subreddit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subreddit
      @subreddit = Subreddit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subreddit_params
      params.require(:subreddit).permit(:title, :slug)
    end
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/views/subreddits/_form.html.erb
<%= form_for(@subreddit) do |f| %>
  <% if @subreddit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subreddit.errors.count, "error") %> prohibited this subreddit from being saved:</h2>

      <ul>
      <% @subreddit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subreddits/_subreddit.html.erb
<li><%= link_to "r/#{subreddit.name}", subreddit %></li>

app/views/subreddits/_subscribe.html.erb
<%= form_for(current_user.subscriptions.build,
                                    remote: true) do |f| %>
  <div><%= hidden_field_tag :subreddit_id, @subreddit.id %></div>
  <%= f.submit "Subscribe", class: "btn btn-primary" %>
<% end %>

app/views/subreddits/_subscription_form.html.erb
<div id="subscribe_form">
  <% if current_user.subscribed_to?(@subreddit) %>
    <%= render 'unsubscribe' %>
  <% else %>
    <%= render 'subscribe' %>
  <% end %>
</div>

app/views/subreddits/_unsubscribe.html.erb
<%= link_to "New post", new_subreddit_submission_path(@subreddit), class: "btn btn-primary" %>
<br><br>
<%= form_for(current_user.subscriptions.find_by(subreddit_id: @subreddit.id),
                                  html: { method: :delete },
                                  remote: true )  do |f| %>
  <%= f.submit "Unsubscribe", class: "btn btn-primary" %>
<% end %>

app/views/subreddits/edit.html.erb
<h1>Editing Subreddit</h1>

<%= render 'form' %>

<%= link_to 'Show', @subreddit %> |
<%= link_to 'Back', subreddits_path %>

app/views/subreddits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subreddits</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subreddits.each do |subreddit| %>
      <tr>
        <td><%= subreddit.title %></td>
        <td><%= link_to 'Show', subreddit_slug_path(subreddit.slug) %></td>
        <td><%= link_to 'Edit', edit_subreddit_path(subreddit) %></td>
        <td><%= link_to 'Destroy', subreddit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subreddit', new_subreddit_path %>

app/views/subreddits/new.html.erb
<h1>New Subreddit</h1>

<%= render 'form' %>

<%= link_to 'Back', subreddits_path %>

app/views/subreddits/show.html.erb
<p>
  <strong><%= @subreddit.title %></strong>
</p>
<ol>
  <%= render @subreddit.articles %>
</ol>

<%= link_to "New Article", new_subreddit_article_path(@subreddit) %>